### ISSUE TITLE
[CI] - CXF + Quarkus main

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkiverse#14]
This issue will be opened and closed dependent on the state of quarkiverse/quarkiverse-cxf building against Quarkus master SNAPSHOT.

If you have interest in being notified of this, please subscribe to the issue.

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkiverse-cxf/actions/runs/341053821

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkiverse-cxf/actions/runs/452070285

**Comment by dufoli** [comment]
Build fixed

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkiverse-cxf/actions/runs/453967086

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/560040736

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/567474714

**Comment by dufoli** [comment]
fixed

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/570581614

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/731931854

**Comment by dufoli** [comment]
@quarkiversebot help

**Comment by dufoli** [comment]
@gastaldi is it possible to trigger a new build by commenting like @quarkiversebot rebuild ?

**Comment by gastaldi** [comment]
@dufoli no, unfortunately. You should be able to trigger  the build manually in your repository: https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-snapshot.yaml . I pushed the changes there (it wasn't updated)

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/739153051

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/1680905449

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/1686028855

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/3993183988

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/3993185979

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4003024792

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4003026858

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4012445544

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4012446765

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4021721837

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4040758040

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4040759518

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4050933129

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4050934409

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4061125079

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4071425589

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4071423836

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4081270191

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4081268514

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4100538764

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4249587732

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4259521976

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4259523377

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/4279074137

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/4279076410

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5397422882

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5408661658

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5419469418

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5440762036

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5450993900

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5460656926

**Comment by dufoli** [comment]
@ppalaga @shumonsharif there is an issue with CI on last quarkus

**Comment by ppalaga** [comment]
@gastaldi I do not see anything Quarkus CXF related in https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5460656926  

Is it perhaps some sort of a misconfig that quarkus-dashbuilder issues get reported here?

I actually never heart of quarkus-dashbuilder. Maybe it is somehow related to CXF?

**Comment by gastaldi** [comment]
You're right, the issue is wrong: https://github.com/quarkusio/quarkus-ecosystem-ci/blob/main/quarkiverse-dashbuilder/info.yaml#L4

https://github.com/quarkusio/quarkus-ecosystem-ci/pull/137 should fix this

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/12880440128

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/12901551264

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/12922619593

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13024934843

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13045967079

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13150594478

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13172173590

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13193551694

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13233907831

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13256214544

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13278438816

**Comment by ppalaga** [comment]
@gsmet we are now in a situation where Quarkus CXF main does not pass against the current Quarkus main due to a known reason, that is handled in our quarkus-main branch. Could we please stop using Quarkiverse CI and start using our [quarkus-main rebase](https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-main-rebase.yml) workflow? The issue that gets updated is this one: https://github.com/quarkiverse/quarkus-cxf/issues/1287

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13300789353

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13322863852

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13363242739

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13581689144

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13623782240

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/13646612623

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14073571010

**Comment by holly-cummins** [comment]
This failure is possibly caused by https://github.com/quarkusio/quarkus/pull/34681. I will investigate.

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14096933293

**Comment by holly-cummins** [comment]
Looks like the failure is unrelated to #34681: 

```
2025-03-26T01:59:09.0915500Z Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
2025-03-26T01:59:09.0917932Z /home/runner/work/quarkus-cxf/quarkus-cxf/current-repo/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/CxfTlsConfiguration.java:[17,8] io.quarkiverse.cxf.CxfTlsConfiguration is not abstract and does not override abstract method getName() in io.quarkus.tls.TlsConfiguration
```

Perhaps it's caused by https://github.com/quarkusio/quarkus/pull/46961?

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14120101351

**Comment by ppalaga** [comment]
Thanks for the heads up, @holly-cummins ! It made me aware that our other Quarkus main branch integration job, that I actually watch and where fix failures, does not reopen its [associated issue](https://github.com/quarkiverse/quarkus-cxf/issues/1287). I have pushed a fix to our [quarkus-main branch](https://github.com/quarkiverse/quarkus-cxf/commits/quarkus-main/). Let's see whether the CI gets green now https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-main-rebase.yml

**Comment by ppalaga** [comment]
The bottom line is that I'd prefer to unify on [our job](https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-main-rebase.yml) and stop using this one. Ours is better, because it is bound to a branch containing fixes specific to the current Quarkus main and it  can also rebase the branch.

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14162237780

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14185117964

**Comment by ppalaga** [comment]
A periodic note that I'd prefer to sunset this issue and the associated job replacing it with https://github.com/quarkiverse/quarkus-cxf/issues/1287 and https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-main-rebase.yml respectively. The fix for the current backwards incompatibility in Quarkus main branch is available in our [quarkus-main](https://github.com/quarkiverse/quarkus-cxf/commits/quarkus-main/) branch.

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14209583870

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14233037320

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14608024479

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14631512764

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14786910938

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14827368506

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14849814574

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14873197997

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14919527290

**Comment by quarkiversebot** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/14961938027

**Comment by quarkiversebot** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15010292154

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15034657253

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15058698322

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15102365478

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15126864377

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15151512523

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15176105988

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15200329222

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15244292892

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15264759572

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15289440423

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15314247197

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15337228147

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15381887601

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15406500013

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15431511495

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15456384714

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15480861397

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15524847019

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15548520457

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15573993996

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15599520898

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15624415071

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15669813903

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15695922149

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15721802849

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15747320352

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15769296993

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15813210631

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15839031139

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15865247189

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15890909109

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15916135128

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15961836328

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/15987612911

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/16014014688

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/16039540167

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/16063912822

**Comment by quarkiversebot** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkiverse/quarkus-cxf/actions/runs/16105574239
